# Generated by Django 3.1.1 on 2020-09-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_id', models.IntegerField(db_index=True, help_text='Id of the tree this category is attached to.', verbose_name='tree id')),
                ('title', models.CharField(blank=True, db_index=True, default='', help_text='Name for the category. Limited to 255 characters.', max_length=255)),
                ('slug', models.SlugField(blank=True, default='', help_text='Short name for use in urls.', max_length=64)),
                ('description', models.CharField(blank=True, default='', help_text='Description of the category. Limited to 255 characters.', max_length=255)),
                ('weight', models.PositiveSmallIntegerField(blank=True, db_index=True, default=0, help_text='Priority for display of several categories Lower value orders first. 0 to 32767.')),
            ],
        ),
        migrations.CreateModel(
            name='TermElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField(db_index=True, help_text='A category associated with an element.', verbose_name='term id')),
                ('eid', models.IntegerField(db_index=True, help_text='An element associated with a category.', verbose_name='element id')),
            ],
        ),
        migrations.CreateModel(
            name='TermParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField(db_index=True, help_text='Category parented by another category.', verbose_name='term id')),
                ('pid', models.IntegerField(blank=True, db_index=True, default=-1, help_text='Category parenting another category.', verbose_name='parent term id')),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, default='', help_text='Name for a tree of categories. Limited to 255 characters.', max_length=255)),
                ('slug', models.SlugField(blank=True, default='', help_text='Short name for use in urls.', max_length=64)),
                ('description', models.CharField(blank=True, default='', help_text='Overall description of the tree of categories. Limited to 255 characters.', max_length=255)),
                ('is_single', models.BooleanField(blank=True, default=True, help_text='Single or many parents for a category in the tree (True = one only, False = many).', verbose_name='terms are single_parent')),
                ('is_unique', models.BooleanField(blank=True, default=True, help_text='Sinngle or many parents for a value attached to the tree catagories (True = one only, False = many).', verbose_name='attached elements are unique')),
                ('weight', models.PositiveSmallIntegerField(blank=True, db_index=True, default=0, help_text='Priority for display of the categories. Lower value orders first. 0 to 32767.')),
            ],
        ),
    ]
