# Generated by Django 3.1.1 on 2020-10-02 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='tree_id',
            new_name='taxonomy_id',
        ),
    ]
