# Generated by Django 3.1.1 on 2020-10-02 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_auto_20201002_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='depth',
        ),
    ]
